name: medical_helper
description: "A medical helper application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  flutter_local_notifications: ^16.3.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  intl: ^0.19.0
  fl_chart: ^0.65.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  timezone: ^0.9.2
  pdf: ^3.10.7
  path_provider: ^2.1.2
  encrypt: ^5.0.3
  qr_flutter: ^4.1.0
  password_strength: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#1ABC9C"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#1ABC9C"
    theme_color: "#1ABC9C"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
