name: medical_helper
description: "A medical helper application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  url_launcher: ^6.2.1
  fl_chart: ^0.65.0
  pdf: ^3.10.7
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  encrypt: ^5.0.3
  qr_flutter: ^4.1.0
  password_strength: ^0.2.0
  firebase_storage: ^11.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
