// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSiw6x9rL1RdbK78r7DtGr2HEZH0_KQI8',
    appId: '1:69222114595:web:a70f546c47853d6f599896',
    messagingSenderId: '69222114595',
    projectId: 'medical-helper-se5547',
    authDomain: 'medical-helper-se5547.firebaseapp.com',
    storageBucket: 'medical-helper-se5547.firebasestorage.app',
    measurementId: 'G-EMN91JC3DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4MEiF80xhLiAQmn4DOOR7-0NOD5_DeC8',
    appId: '1:69222114595:android:a343654e20f2539f599896',
    messagingSenderId: '69222114595',
    projectId: 'medical-helper-se5547',
    storageBucket: 'medical-helper-se5547.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1H3lbHO6VAT_Yv_qL6sKRsIpNYXPQAXA',
    appId: '1:69222114595:ios:2c32d954b7e101c1599896',
    messagingSenderId: '69222114595',
    projectId: 'medical-helper-se5547',
    storageBucket: 'medical-helper-se5547.firebasestorage.app',
    iosBundleId: 'com.samueleskenasy.medicalHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1H3lbHO6VAT_Yv_qL6sKRsIpNYXPQAXA',
    appId: '1:69222114595:ios:531ab8cf1da480fe599896',
    messagingSenderId: '69222114595',
    projectId: 'medical-helper-se5547',
    storageBucket: 'medical-helper-se5547.firebasestorage.app',
    iosBundleId: 'com.example.medicalHelper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSiw6x9rL1RdbK78r7DtGr2HEZH0_KQI8',
    appId: '1:69222114595:web:6e4d5dfc1e14a696599896',
    messagingSenderId: '69222114595',
    projectId: 'medical-helper-se5547',
    authDomain: 'medical-helper-se5547.firebaseapp.com',
    storageBucket: 'medical-helper-se5547.firebasestorage.app',
    measurementId: 'G-CQDHNVWD6S',
  );

}